services:
  redis-node-1:
    image: redis:6.0.8
    container_name: redis-node-1
    command: redis-server --port 6381 --cluster-enabled yes --appendonly yes
    volumes:
      - ./data/redis-node-1/data:/data
    network_mode: host

  redis-node-2:
    image: redis:6.0.8  
    container_name: redis-node-2
    command: redis-server --port 6382 --cluster-enabled yes --appendonly yes
    volumes:
      - ./data/redis-node-2/data:/data
    network_mode: host

  redis-node-3:
    image: redis:6.0.8    
    container_name: redis-node-3
    command: redis-server --port 6383 --cluster-enabled yes --appendonly yes
    volumes:
      - ./data/redis-node-3/data:/data
    network_mode: host

  redis-node-4:
    image: redis:6.0.8    
    container_name: redis-node-4
    command: redis-server --port 6384 --cluster-enabled yes --appendonly yes
    volumes:
      - ./data/redis-node-4/data:/data
    network_mode: host

  redis-node-5:
    image: redis:6.0.8
    container_name: redis-node-5
    command: redis-server --port 6385 --cluster-enabled yes --appendonly yes
    volumes:
      - ./data/redis-node-5/data:/data
    network_mode: host

  redis-node-6:
    image: redis:6.0.8
    container_name: redis-node-6
    command: redis-server --port 6386 --cluster-enabled yes --appendonly yes
    volumes:
      - ./data/redis-node-6/data:/data
    network_mode: host
